from typing import Tuple, Optional

class node:
    "PyNode"
    def __new__(self, array): ...
    @property
    def ndim(self) -> int :...
    @property
    def shape(self) -> Tuple[int] :...
    @property
    def strides(self) -> Tuple[int] :...
    
    def reshape(self, shape: Tuple[int, ...], *, copy: bool = True) -> 'node': ...
    def squeeze(self, *, copy: bool = True) -> 'node': ...
    def transpose(self, *, copy: bool = True) -> 'node': ...
    def swapaxes(self, axis1: int, axis2: int, *, copy: bool = True) -> 'node': ...
    def matrix_transpose(self, *, copy: bool = True) -> 'node': ...