from typing import Tuple

class node:
    "PyNode"
    def __new__(self, array): ...
    @property
    def ndim(self) -> int :...
    @property
    def shape(self) -> Tuple[int] :...
    @property
    def strides(self) -> Tuple[int] :...
    @property
    def itemsize(self) -> int :...