CC = gcc
CFLAGS = -I./inlcude/

SRC_NOUR_DIR = ./src/nour
INCLUDE_NOUR_DIR = ./inlcude/nour
BUILD_DIR = $(SRC_NOUR_DIR)/build
OBJ_DIR = $(BUILD_DIR)/obj
LIB_DIR = $(BUILD_DIR)/lib

all : 

make_dir: 
	mkdir -p $(BUILD_DIR) $(OBJ_DIR) $(LIB_DIR)

clean:
	rm -f $(BUILD_DIR)